workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get --no-example
      - name: Run tests
        script: |
          flutter test --no-pub
      - name: Build APK with specific target
        script: |
          flutter build apk --release --target-platform android-arm64 --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    publishing:
      email:
        recipients:
          - user@example.com

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get --no-example
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Run tests
        script: |
          flutter test --no-pub
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
