workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get --no-example
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Build for iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - user@example.com
