name: didines
description: "A chemistry calculator app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0  # Pour les requêtes HTTP
  connectivity_plus: ^5.0.2  # Pour vérifier la connexion internet
  shared_preferences: ^2.2.2  # Pour sauvegarder les composés trouvés
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
